### ISSUE TITLE
getting wrong action context for module

### ISSUE THREAD

**Issue by kallebertell** [paleo/direct-vuex#11]
I'm receiving the getting wrong action context for modules which are not namespaced.
It is typed correctly, but the actual context at runtime is different than expected. 

I'm guessing if it's not namespaced, the dispatch function is the same across the context for non-namespaced modules. Since it is used as a cache key the following line could return the wrong actionContext:
https://github.com/paleo/direct-vuex/blob/master/src/direct-vuex.ts#L164

**Comment by paleo** [comment]
Hi, you are correct. Can you update and try again? I used the context `state` as a key instead of `dispatch`.

Notice that there is another solution: you could use the context factory of the parent module (or store) in the non-namespaced child.

**Comment by paleo** [comment]
I close the issue. It's probably fixed.

**Comment by kallebertell** [comment]
Yes, seems to have fixed it. Thank you, and thanks for this library.
