### ISSUE TITLE
How to mock context object?

### ISSUE THREAD

**Issue by mspoulsen** [paleo/direct-vuex#12]
Hi, 

I would like to test an action similar to this:

```javascript
async myAction(context: any,): Promise<void> {
    const { commit, rootDispatch, getters } = typedContext(context)

    if (!getters.someProperty) {
        rootDispatch.uiModule.notification("My message")
    }

    commit.DO_SOMETHING()
}
````

I am struggling on how to mock the context object in my test that I need to pass to my action.

```javascript
test("myAction", async () => {
    const context = {
      ...store,
      commit: jest.fn()
    }

    await actions.myAction(context)

    expect(context.commit).toHaveBeenCalledWith("DO_SOMETHING")
  })
````

I have tried the above. But the getters returned from typedContext is an empty object.

What is the easiest way to mock to context object? :)

**Comment by paleo** [comment]
> But the getters returned from typedContext is an empty object.

Are you sure this issue is different of https://github.com/paleo/direct-vuex/issues/6#issuecomment-561543560 ?

**Comment by mspoulsen** [comment]
Yes, it is not the same. 

My question is: how do I create the context object if I have a store?

I have a store initialized when I setup my tests, but the context object is not the same as the store object (although very similar). How can I (given a store) create a context object that I use in my tests to pass to my actions, so that typedContext (my name for mod1ActionContext) returns the same functions (dispatch, commit, getters etc) as the app would.

A few examples on how to test actions and getters when using direct-vuex would be very helpful :smiley:

**Comment by paleo** [comment]
```ts
    const context = {
      ...store,
      commit: jest.fn()
    }
```

Is it a valid way to test a Vuex action? The context object should not contain the store. In particular, the `state` property is invalid if you are in a namespaced module.

**Comment by paleo** [comment]
@mspoulsen Is this issue still relevant?
