### ISSUE TITLE
How to test rootDispatch?

### ISSUE THREAD

**Issue by mspoulsen** [paleo/direct-vuex#13]
This is my action:

```javascript 
async foo(context: any): Promise<void> {
    const { rootDispatch } = typedContext(context)
    rootDispatch.uiModule.notification("test")
  }
````

And this is my test:

```javascript 
test.only("foo", async () => {
    const dispatch = jest.fn()
    await actions.foo({ dispatch })

    expect(dispatch).toHaveBeenCalledWith("uiModule/notification", "test")
  })
````

Expected: test to pass
Actual: Number of calls: 0

What am I doing wrong here? 
Thanks!

**Comment by paleo** [comment]
The actual `rootDispatch` from Direct-Vuex doesn't use `rootDispatch` from the context, but the store dispatch instead. I will think about how to really use the context, while avoiding regenerating the root wrappers for each module.

**Comment by mspoulsen** [comment]
So no way to test rootDispatch at the moment?

**Comment by mspoulsen** [comment]
Let me elaborate:

If I use the old syntax:

```javascript
foo(context: any) {
  context.dispatch("barModule/baz", undefined, { root: true })
}
```
Then I can add a test like this:
```javascript
test("foo triggers barModule/baz", async () => {
  const dispatch = jest.fn()
  await actions.foo({ dispatch })
  expect(dispatch).toHaveBeenCalledWith("barModule/baz", undefined, {
    root: true
  })
})
```

But if I use direct-vuex:
```javascript
foo(context: any) {
    const { rootDispatch } = typedContext(context)
    rootDispatch.barModule.baz()
  },
```

Then my test fails and I do not know how to test this?

Thanks for your patience with me in advance :smiley: 
Vuex is a real pain for TS users and I really appreciate your attempt to make our lives easier until they change their api.

**Comment by paleo** [comment]
I updated Direct-vuex to really use the local context object. Can you update and try again?

**Comment by mspoulsen** [comment]
It's working :+1: Thank you very much!

**Comment by paleo** [comment]
You're welcome. I think I can close the issue. :)
