### ISSUE TITLE
Please bundle module/browser version (like vuex.min.js format)

### ISSUE THREAD

**Issue by viT-1** [paleo/direct-vuex#14]
Can't use [in browser](https://cdn.jsdelivr.net/npm/direct-vuex@0.8.6/dist/direct-vuex.js), cause of error:
```
Uncaught ReferenceError: exports is not defined
    at direct-vuex.js:5

```

I am using SystemJs for production (with ie11 support) bundle with `type="systemjs-importmap"` like this:
```
{
	"imports": {
		"direct-vuex": "https://cdn.jsdelivr.net/npm/direct-vuex@0.8.6/dist/direct-vuex.min.js",
		"vue": "https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.min.js",
		"vuex": "https://cdn.jsdelivr.net/npm/vuex@3.1.2/dist/vuex.min.js",
		"wretch": "https://cdn.jsdelivr.net/npm/wretch@1.6.0/dist/bundle/wretch.min.js"
	}
}
```

and all ok except direct-vuex =(

**Comment by paleo** [comment]
Please update to the version `0.9` and let me know if it is complete.

**Comment by viT-1** [comment]
I have experience with [vue-property-decorator umd](https://www.jsdelivr.com/package/npm/vue-property-decorator) package [under SystemJS](https://github.com/viT-1/systemjs-ts-es6-vue/blob/master/gulpfile.esm.js#L186), but forced to bundle it (can't use cdn).
With umd of direct-vuex I have same problem.
When I use umd in systemjs-importmap I have Error:
`direct_vuex_1.createDirectStore is not a function`
=(
Can you publish not only umd module, but standard as `vuex.min.js` also?

**Comment by viT-1** [comment]
AMD for SystemJs is Ok, but [UMD is not](https://github.com/systemjs/systemjs/issues/1933).

**Comment by paleo** [comment]
In `vuex.js` there is the following code:

```js
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
  typeof define === 'function' && define.amd ? define(factory) :
  (global = global || self, global.Vuex = factory());
}(this, function () { 'use strict';
```

I thought this code was the UMD format.

The solution becomes unclear for me. I thought UMD was simultaneously AMD and CommonJS. And I thought SystemJS could load any format. I don't know how to solve the issue for the moment.

**Comment by paleo** [comment]
TypeScript generates this code for UMD:

```js
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
(function (factory) {
    if (typeof module === "object" && typeof module.exports === "object") {
        var v = factory(require, exports);
        if (v !== undefined) module.exports = v;
    }
    else if (typeof define === "function" && define.amd) {
        define(["require", "exports", "vuex"], factory);
    }
})(function (require, exports) {
    "use strict";
```

And for AMD:

```js
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
define(["require", "exports", "vuex"], function (require, exports, vuex_1) {
    "use strict";
```

There is a [compiler option](https://www.typescriptlang.org/docs/handbook/compiler-options.html) `System` that generates this code:

```js
System.register(["vuex"], function (exports_1, context_1) {
    "use strict";
```

I could publish a bundle for the `system` module format if you want. But I'm really surprised that `dist/direct-vuex.esm.js` or the UMD format can't be loaded.

**Comment by viT-1** [comment]
>But I'm really surprised that `dist/direct-vuex.esm.js`

[Ticket about esm.js](https://github.com/paleo/direct-vuex/issues/7) is ok.

**Comment by viT-1** [comment]
I know about compiler option & [use it](https://github.com/viT-1/systemjs-ts-es6-vue/blob/master/src/tsconfig.json#L4). I want to link to your module in importmap (and don't to bundle it as SystemJS module like I do [with vue-property-decorator](https://github.com/viT-1/systemjs-ts-es6-vue/blob/master/src/tsconfig.json#L12) from its [src](https://cdn.jsdelivr.net/npm/vue-property-decorator@8.3.0/lib/vue-property-decorator.js)), but systemjs-importmap is not working with umd format.

**Comment by paleo** [comment]
I just published a new version using Rollup.
Maybe the Rollup version of UMD is better.
And I added a System version from Rollup too.
Can you update and test again?

**Comment by viT-1** [comment]
It is unconfortable: to add script with src to systemjs bundle, in comparison with [systemjs-importmap](https://github.com/systemjs/systemjs#import-maps) where I have cdn links to all assets.

**Comment by viT-1** [comment]
Just tested in IE11.
`Syntax error on direct-vuex.system.min.js (1,384)`
cause of ES6 `=>` instead of ES5

**Comment by paleo** [comment]
Try to update to 0.9.3. The versions for UMD and SystemJS are now in ES5 syntax. I use a `WeakMap`, but it should be [OK with IE 11](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap#Browser_compatibility).

> It is unconfortable: to add script with src to systemjs bundle, in comparison with [systemjs-importmap](https://github.com/systemjs/systemjs#import-maps) where I have cdn links to all assets.

I'm not sure to understand. [This CDN](https://cdn.jsdelivr.net/npm/direct-vuex@0.9.3/dist/) is not enough?

**Comment by viT-1** [comment]
> I'm not sure to understand. This CDN is not enough?

Yes:
- esm only for `<script type="module">`, not IE (only for dev mode in modern browsers)
- system (v0.9.3) is working but compare to other packages with native bundle it needs to make personal configuration: additional link to cdn. It will be better to use direct-vuex through systemjs-importmap  (for [example](https://github.com/viT-1/systemjs-ts-es6-vue/blob/master/src/importmap.system.json)) with link to native (supported IE11) browser format
- umd is not supported on systemjs-importmap

**Comment by viT-1** [comment]
Strange, but [wretch is working](https://cdn.jsdelivr.net/npm/wretch@1.6.0/dist/bundle/wretch.min.js) also, despite of [umd format](https://github.com/elbywan/wretch#usage).

**Comment by viT-1** [comment]
SystemJs bundle of direct-vuex is not necessary. I have single bundle by systemjs only for project files & two packages/assets: vue-class-component (cause of additional replacing `process.env.NODE_ENV` code) & vue-property-decorator (cause of umd format). Other assets for production with supporting IE11 are linking through systemjs-importmap.

No Babel, no webpack, no rollup, only tsc/ttsc transpiling with typescript-transform-paths for  alias imports resolving, esm & systemjs bundling.

**Comment by paleo** [comment]
I'm not sure of what is needed now. I can remove the useless system bundle. But after that, if you need something else, you'll have to be explicit. I don't use SystemJS personally, nor IE11. I use Webpack, which automatically uses the ESM module version when it exists and it is just fine.

**Comment by viT-1** [comment]
@paleo To have SystemJS bundle is better (I tested, is working) than have only unsupported (by SystemJS) umd module. But for browser it will be better to have working standard version ;)

If I use `import { createDirectStore } from 'direct-vuex';` & importmap with
- umd and typescript code I have error:
`Uncaught TypeError: Cannot read property 'createDirectStore' of undefined`
- [direct-vuex.min.js](https://cdn.jsdelivr.net/npm/direct-vuex@0.8.7/dist/direct-vuex.min.js) v0.8.7 I have error: direct-vuex.js (stackoverflow [explained](https://stackoverflow.com/questions/43042889/typescript-referenceerror-exports-is-not-defined)):
```
Uncaught (in promise) ReferenceError: exports is not defined
    at direct-vuex.js:5

```
on `Object.defineProperty(exports, "__esModule", { value: true });`

And this is script that I want to, but similar transpiled syntax as I have in [vuex.min.js](https://cdn.jsdelivr.net/npm/vuex@3.1.2/dist/vuex.js) (for example).

It will be better to have dist with three versions:
- esm for modern browsers
- umd for NodeJs or RequireJs
- standard for IE11 and so on (case of esm unsupported), which can be running on browser
straight from the `<script src=".../direct-vuex.min.js">` with ES5
& without forcing developer to any bundling or having special loaders
(like 0.8.7 version transpiled but needs to be fixed)

**Comment by paleo** [comment]
> [direct-vuex.min.js](https://cdn.jsdelivr.net/npm/direct-vuex@0.8.7/dist/direct-vuex.min.js) v0.8.7 I have error: direct-vuex.js (stackoverflow [explained](https://stackoverflow.com/questions/43042889/typescript-referenceerror-exports-is-not-defined)):

In Direct-vuex 0.8, the main bundle was exported with CommonJS.

> And this is script that I want to, but similar transpiled syntax as I have in [vuex.min.js](https://cdn.jsdelivr.net/npm/vuex@3.1.2/dist/vuex.js) (for example).

The last [direct-vuex.umd.js](https://cdn.jsdelivr.net/npm/direct-vuex@0.9.3/dist/direct-vuex.umd.js) and [vuex.js](https://cdn.jsdelivr.net/npm/vuex@3.1.2/dist/vuex.js) have the same module system. It is a UMD format, produced by Rollup. Maybe I can define better settings for global variables.

>     * standard for IE11 and so on (case of esm unsupported), which can be running on browser
>       straight from the `<script src=".../direct-vuex.min.js">` with ES5
>       & without forcing developer to any bundling or having special loaders

Which [Vuex bundles](https://cdn.jsdelivr.net/npm/vuex@3.1.2/dist/) do you use for this case?

**Comment by viT-1** [comment]
[This Vuex](https://cdn.jsdelivr.net/npm/vuex@3.1.2/dist/vuex.min.js) bundle is working for me (through systemjs-importmap), about this was [initial message](https://github.com/paleo/direct-vuex/issues/14#issue-539769657).

**Comment by paleo** [comment]
> [This Vuex](https://cdn.jsdelivr.net/npm/vuex@3.1.2/dist/vuex.min.js) bundle is working for me (through systemjs-importmap), about this was [initial message](https://github.com/paleo/direct-vuex/issues/14#issue-539769657).

So, [this one](https://cdn.jsdelivr.net/npm/direct-vuex@0.9.3/dist/direct-vuex.umd.min.js) for Direct-vuex should work. It is a UMD from Rollup, with legacy JS (`var` etc.). Except the usage of a `WeakMap` but IE11 has an implementation of `WeakMap`.

**Comment by viT-1** [comment]
I am testing on Chrome 79.0.3945.79 first, and then on IE11.
And I have no success even with Chrome on umd format because of `Uncaught TypeError: Cannot read property 'createDirectStore' of undefined`

**Comment by paleo** [comment]
With version 0.8 or 0.9?

**Comment by viT-1** [comment]
0.9.3

**Comment by paleo** [comment]
Can I have a minimal but complete example of your code?

**Comment by viT-1** [comment]
I have not published any minimal project with vuex yet =( It will take a time.

**Comment by paleo** [comment]
I actually just need a minimal code that reproduces the error:

> Uncaught TypeError: Cannot read property 'createDirectStore' of undefined

**Comment by viT-1** [comment]
Ok, I'm working on it

**Comment by viT-1** [comment]
Done! You can compare [initial commit](https://github.com/viT-1/direct-vuex-systemjs/tree/504f3a0d9b8809179885aa8dcaa643006171268f) without direct-vuex is working, but [2nd commit](https://github.com/viT-1/direct-vuex-systemjs/blob/b1ca71824eb34f0ccc6d9f2697455ebdfda732cf/src/VueApp.ts#L16) with direct-vuex is not working. And it's all about umd format, vuex through systemjs-importmap is ok =(

- `npm run deploy`
- run browser with `http://localhost:3000/`

**Comment by viT-1** [comment]
It's may be everything is ok with straight umd to index.html ([like fetch.umd](https://github.com/viT-1/direct-vuex-systemjs/blob/b1ca71824eb34f0ccc6d9f2697455ebdfda732cf/src/index.html#L8) for IE11),
but [SystemJS can't use umd format](https://github.com/systemjs/systemjs/issues/1933) in systemjs-importmap, it is my issue - I need simple ES5 (not commonJs) bundle for that mapping.

**Comment by paleo** [comment]
Thanks. I see the problem:

```js
import { createDirectStore } from 'direct-vuex';
import defaultDv from 'direct-vuex';
import * as allDv from 'direct-vuex';

console.log("createDirectStore", createDirectStore);
console.log("defaultDv", defaultDv);
console.log("allDv", allDv);
```

All the Direct-vuex functions are erroneously imported as sub-properties of the `default` export. I don't know if it is a wrong configuration of Rollup or something else. I will search tomorrow.

**Comment by paleo** [comment]
There is nothing to do. It seems SystemJS always imports a module as `default`. Here is how to tell TS to deal with it:

In `tsconfig.system.json`, add a compiler option:
```json
  "esModuleInterop": true
```

In `VueApp.ts`, import DirectVuex as `default`, then use it:

```ts
import DirectVuex from 'direct-vuex';
// …
  const store = DirectVuex.createDirectStore(storeConf).store.original;
```

**Comment by viT-1** [comment]
Yes, [it's working](https://github.com/viT-1/direct-vuex-systemjs/commit/aa789daabe5b0e7d3480383e031437c50e559af0) (only defaults but it is acceptable). Thank you very much!

**Comment by viT-1** [comment]
v 0.9.4
It's working only with SystemJS.
But esm version (& jest testing) using as `import DirectVuex from 'direct-vuex';` raise error:
`Uncaught SyntaxError: The requested module '/direct-vuex.esm.min.js' does not provide an export named 'default'`
