### ISSUE TITLE
Module "type not assignable" error

### ISSUE THREAD

**Issue by eschirtz** [paleo/direct-vuex#15]
Hey,

Just read your Medium article and I'm looking forward to using this package! Unfortunately I'm running into an issue creating the direct store.

Below is the main index.ts for my store: `store/index.ts`

```ts
import Vue from 'vue';
import Vuex, { StoreOptions } from 'vuex';
import { createDirectStore } from 'direct-vuex';
import { RootState } from './types';
import profile from './profile';

Vue.use(Vuex);

const { store } = createDirectStore({
  state: {},
  modules: {
    profile,
  },
});

export default new Vuex.Store<RootState>(store);

```

And here is a module that I am trying to include in the store: `store/profile/index.ts`
```ts
import { Module } from 'vuex';
import getters from './getters';
import actions from './actions';
import mutations from './mutations';
import { ProfileState } from './types';
import { RootState } from '../types';


const state: ProfileState = {
  user: undefined,
  authErrorMessage: '',
  authLoading: false,
};

const profile: Module<ProfileState, RootState> = {
  namespaced: true as true,
  state: {
    user: undefined,
    authErrorMessage: '',
    authLoading: false,
  },
  getters,
  actions,
  mutations,
};

export default profile;

```

The `modules` property in `store/index.ts` (rather the `profile` property) is causing a type assignability error.

```
Type '{ profile: Module<ProfileState, RootState>; }' is not assignable to type '{ profile: Module<ProfileState, RootState>; } & ModulesImpl<any>'.
  Type '{ profile: Module<ProfileState, RootState>; }' is not assignable to type 'ModulesImpl<any>'.
    Property 'profile' is incompatible with index signature.
      Type 'Module<ProfileState, RootState>' is not assignable to type 'ModuleOptions<any>'.
        Types of property 'actions' are incompatible.
          Type 'ActionTree<ProfileState, RootState> | undefined' is not assignable to type 'ActionsImpl | undefined'.
            Type 'ActionTree<ProfileState, RootState>' is not assignable to type 'ActionsImpl'.
              Index signatures are incompatible.
                Type 'Action<ProfileState, RootState>' is not assignable to type 'ActionImpl'.
                  Type 'ActionObject<ProfileState, RootState>' is not assignable to type 'ActionImpl'.
                    Type 'ActionObject<ProfileState, RootState>' provides no match for the signature '(context: ActionContext<any, any>, payload: any): any'.ts(2322)
index.ts(11, 3): The expected type comes from property 'modules' which is declared here on type '{ state: {}; modules: { profile: Module<ProfileState, RootState>; }; } & StoreOptions<{}>'
``` 

Any help would be great! I am happy to provide more details.

Thanks,

**Comment by paleo** [comment]
Hi,

Do not use type definitions from Vuex (`StoreOptions`, `Module`). These definitions prevent from inferring the details of the store implementation.

I suggest to use `createModule`:

```ts
import { createModule } from "direct-vuex";

const profile = createModule({
  namespaced: true, // 'as true' is not needed when using 'createModule'
  // …
})
```

See also [the documentation](https://github.com/paleo/direct-vuex#implement-a-vuex-store-with-typed-helpers).

Additionally, this line can't work:

```ts
export default new Vuex.Store<RootState>(store);
```

Your implementation of `store/index.ts` must follow [the documentation](https://github.com/paleo/direct-vuex#create-the-store):

```ts
// store/index.ts
import Vue from "vue"
import Vuex from "vuex"
import { createDirectStore } from "direct-vuex"
import profile from './profile';

Vue.use(Vuex);

const { store, rootActionContext, moduleActionContext } = createDirectStore({
  modules: {
    profile,
  },
});

// Export the direct-store instead of the classic Vuex store.
export default store;

// The following exports will be used to enable types in the
// implementation of actions.
export { rootActionContext, moduleActionContext };

// The following lines enable types in the injected store '$store'.
export type AppStore = typeof store;
declare module "vuex" {
  interface Store<S> {
    direct: AppStore
  }
}
```

Notice that your `RootState` could be inferred:

```ts
export type AppState = AppStore["state"];
```

**Comment by eschirtz** [comment]
Ah, that makes sense. Thanks a lot!

**Comment by eschirtz** [comment]
How do you avoid cyclic dependencies with regards to the `moduleActionContext` that is exported from the root store and then imported in a submodule? Since the root store imports the sub module that forms a cycle. 

Looking at the documentation the module imports as `import { moduleActionContext } from "./store"` but the `./store` is the file that exports, `export { rootActionContext, moduleActionContext }`

( I can open a new issue for this question if you would like )

**Comment by paleo** [comment]
> How do you avoid cyclic dependencies

I couldn't avoid them.

```ts
export const mod1ActionContext = (context: any) => moduleActionContext(context, mod1)
```

It works because `mod1ActionContext` is not executed at the same time it is declared. It is executed when an action is executed, ie. after all the store and modules are already initialized.

**Comment by paleo** [comment]
A consequence is the `store` source file must be imported first from the rest of the application. If you import a module first, you can run into [this kind of issue](https://github.com/paleo/direct-vuex/issues/6#issuecomment-561543560).

**Comment by eschirtz** [comment]
Make sense, thanks! Everything seems to be working well now
