### ISSUE TITLE
Mistake in documentation? Variable used before it's assigned. + What's the work around?

### ISSUE THREAD

**Issue by kevin-courbet** [paleo/direct-vuex#16]
Hey. In the module sample on how to use moduleActionContext, mod1ActionContext is used before it's assigned.
```
actions: {
    loadP1(context, payload: { id: string }) {
      const { dispatch, commit, getters, state } = mod1ActionContext(context)
      // Here, 'dispatch', 'commit', 'getters' and 'state' are typed.
    }
  },
})

export default mod1
export const mod1ActionContext = (context: any) => moduleActionContext(context, mod1)
```
Problem is, moduleActionContext requires the module to be created, so you can't create it before either.

My workaround has been to create the module in 2 steps, first creating the module with state & mutations then assigning actions, which is not elegant:
```
const Module = createModule({
  state: (): ModuleState => { // whatever } ,
  getters: { // whatever },
  mutations: { // whatever },
`  actions: {} 
});

export const ModuleActionContext = (context: any) => moduleActionContext(context, Module);

Module.actions = {
  whatever(context: any, payload: { foo: boolean }) {
    const { commit } = ModuleActionContext(context);
    commit.THE_MUTATION(payload.foo);
  }
};
```
Am I seeing something wrong?

**Comment by paleo** [comment]
Hi, Direct-vuex won't be able to infer your actions if you declare them in a second step. It's not a valid workaround.

I don't see a better solution than my current proposition. `mod1ActionContext` has to be declared after the module implementation. I suggest to disable the rule in your linter with a comment at the top of your source file.

With TSLint:
```ts
// tslint:disable: no-use-before-declare
```

With ESLint:
```ts
/*eslint no-use-before-define: ["error", { "functions": false }]*/
```
