### ISSUE TITLE
IE11 not working with umd

### ISSUE THREAD

**Issue by viT-1** [paleo/direct-vuex#19]
Chrome is ok, but IE11 is not.

If I [remove direct-vuex code](https://github.com/viT-1/systemjs-ts-es6-vue/commit/9fc5f15b2421b762439b4795d94bcec99743c7a9), IE11 is ok.
If not, I have error:
```
Unhandled promise rejection TypeError: unsupported method "entries"
stack: 
at gettersFromOptions (https://cdn.jsdelivr.net/npm/direct-vuex@0.9.8/dist/direct-vuex.umd.js:68:30)
at toDirectGetters (https://cdn.jsdelivr.net/npm/direct-vuex@0.9.8/dist/direct-vuex.umd.js:58:13)
at createDirectStore (https://cdn.jsdelivr.net/npm/direct-vuex@0.9.8/dist/direct-vuex.umd.js:18:9)
at e.init (http://localhost:3000/bundle.system.js:1:19479)
...
```

**Comment by viT-1** [comment]
I'll try to check another [simplier project](https://github.com/viT-1/direct-vuex-systemjs), may be this trouble on my side, not direct-vuex.

**Comment by viT-1** [comment]
0.9.3 & 0.9.8 umd with simplier vuex store is ok with IE11. Strange =(

**Comment by paleo** [comment]
Indeed, I use `Object.entries` which is not supported by IE.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries

I could rewrite with `Object.keys`. Or you can add [a polyfill](https://www.npmjs.com/package/es7-object-polyfill).

**Comment by viT-1** [comment]
> I could rewrite with Object.keys

For me it will be nicier to use umd which syntax is supported by IE11...

Can you write your code on modern way, but bundle it for es5 & ie11?
But writing by hands without bundling will be better package size certainly.

**Comment by paleo** [comment]
I updated using `Object.keys`, it is not a big deal. But I'm unsure if there is another standard lib I can't use. Please update and test.

**Comment by viT-1** [comment]
Yes, it [is working now](https://github.com/viT-1/systemjs-ts-es6-vue/commit/ba1d64619d79f27ce90583c3ceb2ed2b60d45d9f), but my code is minimal. If I found another trouble with ie11 support I'll create new issue, thanks! :pray:
