### ISSUE TITLE
Q: How to migrate from dynamic vuex modules to dynamic direct-vuex modules?

### ISSUE THREAD

**Issue by viT-1** [paleo/direct-vuex#20]
I read [your article](https://itnext.io/use-a-vuex-store-with-typing-in-typescript-without-decorators-or-boilerplate-57732d175ff3), and don't understand how to migrate properly.
I am using vue-property-decorator & register component store as module [on beforeCreate hook](https://github.com/viT-1/systemjs-ts-es6-vue/blob/ac8a05e5ccc8e7c5b100a162bd9c874ef29bf9e7/src/unique.blocks/SomeForm/SomeForm.ts#L32):
```
beforeCreate(): void {
	// only if not initialized yet
	const store = this.$store;
	if (!(store && store.state && store.state[storeName])) {
		store.registerModule(storeName, storeConf);
	}
}
```
where storeConf looks like [this](https://github.com/viT-1/systemjs-ts-es6-vue/blob/ac8a05e5ccc8e7c5b100a162bd9c874ef29bf9e7/src/unique.blocks/SomeForm/store/index.ts#L32):
```
import { IState } from './state.i';

const defaultState: IState = {
	iamSelect: {
		value: null,
		data: {
			options: [],
		},
	},
};
...

export const storeConf = {
	namespaced: true as true, // direct-vuex needs
	actions,
	getters,
	mutations,
	state: defaultState,
} as const;
```

I register Store (without modules) only in [app file](https://github.com/viT-1/systemjs-ts-es6-vue/blob/ac8a05e5ccc8e7c5b100a162bd9c874ef29bf9e7/src/VueApp/VueApp.ts#L31) (not migrated totally yet):
`const store = createDirectStore(storeConf).store.original;`

Does direct-vuex support dynamic registration of modules?

**Comment by paleo** [comment]
Hi,

Fyi the documentation [on this repo](https://github.com/paleo/direct-vuex) is more up-to-date than the article on Medium.

Why don't you call `createDirectStore` from `store/index.ts`? You won't be able to expose types inferred in your `init` function.

**Comment by viT-1** [comment]
> Why don't you call createDirectStore from store/index.ts?

Because I want to separate store logic to modules, and don't want to modify main store code (static initialization) for every new added vuex-module (belongs new component).

& because for clear code I should create vuex-store once, therefore I export only storeConfig from every vuex-module, not store. Main store, in my variant, is only container for modules, which is initiated once in [main VueApp logic](https://github.com/viT-1/systemjs-ts-es6-vue/blob/ac8a05e5ccc8e7c5b100a162bd9c874ef29bf9e7/src/VueApp/VueApp.ts#L31), not in store configuration files/modules.

**Comment by paleo** [comment]
How could you add a vuex-module without to update the main store code?

**Comment by viT-1** [comment]
With classical Vuex [I am update main store](https://github.com/viT-1/systemjs-ts-es6-vue/blob/ac8a05e5ccc8e7c5b100a162bd9c874ef29bf9e7/src/unique.blocks/SomeForm/SomeForm.ts#L32) through relating vuex-module like this: `this.$store.registerModule`

**Comment by paleo** [comment]
Ah yes I understand!

Sorry, I'm unsure if it could be possible to infer types with that kind of initialization, maybe using type augmentation. Currently direct-vuex can't work with that.

**Comment by viT-1** [comment]
I'm understand, it is because of main store [have not any information](https://github.com/viT-1/systemjs-ts-es6-vue/blob/ac8a05e5ccc8e7c5b100a162bd9c874ef29bf9e7/src/VueApp/store/index.ts) for `createDirectStore`?

VueApp/store/index.ts:
```
export const storeConf = {
	state: {},
	mutations: {},
	actions: {},
	modules: {
		// dynamic register in every vuex-module
	},
} as const;
```

**Comment by paleo** [comment]
Yes. Direct-vuex does a double inspection of your store/modules options. There is a pure typing inspection that provides inferred types, and a pure runtime inspection that provides wrapper functions. The first one is made at compile time, the second one is made at runtime.

I guess it could be possible to implement something to create wrappers when using `registerModule`. But it won't be easy to do the equivalent job at build time for typing inference!

**Comment by viT-1** [comment]
Thanks. Dynamic register modules is useful, but, in my project, is not so necessary. I'll change my code to use static declaration of modules in main store.

But if your package will be popular still Vue 3.0 released, this feature issue may be raised again ;)
