### ISSUE TITLE
Does this package support SSR?

### ISSUE THREAD

**Issue by jaredmcateer** [paleo/direct-vuex#21]
First of all thanks for your work on this, it is a great looking wrapper for vuex. I'm starting a new app and trying to incorporate server side rendering and am running into a bit of difficult implementing direct-vuex in the pattern defined at https://ssr.vuejs.org/guide/data.html#data-store & https://ssr.vuejs.org/guide/data.html#store-code-splitting

Maybe my inexperience with your library and SSR I'm not seeing a direct solution that would allow me to have a factory function to generate a new store for both the client/server as well as define modules based on the return value of createDirectStore?

**Comment by paleo** [comment]
> Does this package support SSR?

Hi, Maybe, I never tried.

In the documentation, I read that the store is created in a function:

```ts
export function createStore () {
  return new Vuex.Store({
```

You could try something like:

```ts
export function createStore () {
  const { store } = createDirectStore({
    // … store implementation here …
  })
  return store
}

// The following lines enable types in the injected store '$store'.
export type AppStore = ReturnType<typeof createStore>
declare module "vuex" {
  interface Store<S> {
    direct: AppStore
  }
}
```

Notice: After that, don't forget to use `store.original` instead of `store` when you register your store in Vue.

Notice 2: However, I doubt you'll be able to use `moduleActionContext` in the implementation of your vuex modules.

**Comment by jaredmcateer** [comment]
>Notice 2: However, I doubt you'll be able to use moduleActionContext in the implementation of your vuex modules.

Yea that's what I feared, I was hoping I was missing something. I'll think about this some more if I come up with a solution I'll submit a pr with some documentation. Thanks
