### ISSUE TITLE
Q: Why declaring module 'vuex' not in d.ts & why export?

### ISSUE THREAD

**Issue by viT-1** [paleo/direct-vuex#22]
I'm just trying to separate typescript declaration code from runtime code, and have a question about direct-vuex configuration from [readme](https://github.com/paleo/direct-vuex#create-the-store): why you don't use d.ts files for declaring module 'vuex'? What am I losing when [change code](https://github.com/viT-1/systemjs-ts-es6-vue/commit/b1297b39342015ef11d3bcb3639af06d87c84bc2) like this:

[App/store/App.store.d.ts](https://github.com/viT-1/systemjs-ts-es6-vue/commit/b1297b39342015ef11d3bcb3639af06d87c84bc2#diff-dc1d72b05cf9e597443710d419cf1fd4)
```
import { store } from './App.store';

type AppStore = typeof store; // Why export?
declare module 'vuex' {
	interface IAppStore<S> {
		direct: AppStore;
	}
}
```

**Comment by paleo** [comment]
It is not required to export the `AppStore` type. It is just convenient for the rest of the application if you would like, for example, create a helper like: `function doSomethingWithStore(dispatch: AppStore["dispatch"])`.

> why you don't use d.ts files for declaring module 'vuex'?

I think you can.

**Comment by viT-1** [comment]
> I think you can

No, I can't =)
https://github.com/paleo/direct-vuex/issues/28#issuecomment-576695175

**Comment by paleo** [comment]
Indeed. Circular dependencies is hard to handle.

**Comment by viT-1** [comment]
Even so [I moved out](https://github.com/viT-1/systemjs-ts-es6-vue/commit/82172c035041c26a4f54619eedae30863bdeb105) vuex Store extending to `direct-vuex.d.ts` file in typings. Checked code by `npm run lint`, all is ok.
