### ISSUE TITLE
Q: Declaring state

### ISSUE THREAD

**Issue by viT-1** [paleo/direct-vuex#23]
About [declaring state](https://github.com/paleo/direct-vuex#a-limitation-on-how-to-declare-a-state): is it correct to declare state like [this](https://github.com/viT-1/systemjs-ts-es6-vue/blob/b1297b39342015ef11d3bcb3639af06d87c84bc2/src/unique.blocks/SomeForm/store/index.ts#L7)?

```
interface IState {
	iamSelect: {
		value: IamSelectOption | null;
		data: IamSelectData;
	};
}

const defaultState: IState = {
	iamSelect: {
		value: null,
		data: {
			options: [],
		},
	},
};
```

**Comment by viT-1** [comment]
Same as
`const state:  Mod1State = { p1: string };`

If it's correct, please update information in readme.md

**Comment by paleo** [comment]
Yes it's fine. The only syntax that doesn't work is:
```ts
export const storeConf = {
  // …
  state() { return defaultState; }
};
```
