### ISSUE TITLE
Q: Action context & migrate actions realisation from dispatch('smth') to strict type calling actions

### ISSUE THREAD

**Issue by viT-1** [paleo/direct-vuex#24]
For actions I am [using destructuring for readable declarations](https://github.com/viT-1/systemjs-ts-es6-vue/blob/b1297b39342015ef11d3bcb3639af06d87c84bc2/src/unique.blocks/SomeForm/store/actions.ts#L9) in parameters:
```
export const getSomeValues = (
	{ dispatch }: { dispatch: Function },
	{ label }: ISomeValue,
): Promise <Array<ISomeValue> | void> => SomeSvc
	.fetchData({ label })
	.then((resp) => dispatch('setSomeValues', resp));
```

And I have test like [this](https://github.com/viT-1/systemjs-ts-es6-vue/blob/b1297b39342015ef11d3bcb3639af06d87c84bc2/src/unique.blocks/SomeForm/store/actions.spec.ts#L12): 
```
describe('vuex SomeForm IamSelect actions', () => {
	it('getPoints after getting data raise appropriate action', async () => {
		expect.assertions(1);

		const dispatch = jest.fn();
		await actions.getSomeValues({ dispatch }, { label: 'Рим' });

		expect(dispatch).toHaveBeenCalledWith('setSomeValues', expect.anything());
	});
});
```

with stubbing dispatch/commit functions.

I'm [searching](https://github.com/search?q=direct-vuex&type=Code) also another examples of usage direct-vuex, and found [some code](https://github.com/coop-care/web-app/blob/c48ca0292268fcf5f0b5877f7c52bab53e9cc20e/src/store/actions.ts#L8):
```
export default createActions({
    fetchCustomersFromDB(context) {
        const { commit } = rootActionContext(context);
        commit.isLoadingCustomerList(true);
        stitchApi
            .getAllCustomers()
            .then(customers => {
                // console.log("Success:", result);
                commit.customers(customers);
                commit.isLoadingCustomerList(false);
            })
            .catch(err => {
                console.error(`Failed: ${err}`);
                commit.isLoadingCustomerList(false);
            });
    },
});
```

If I declare input parameters in actions through `rootActionContext` or (for Module) through `moduleActionContext` (not with destructing), I can't test actions with jest stubs.

How to declare actions with destructed parameters to get code like `dispatch.action1` instead of `dispatch('action1')`?

**Comment by viT-1** [comment]
Which solution is supposed in related issue?
https://github.com/paleo/direct-vuex/issues/6#issuecomment-562737161

**Comment by paleo** [comment]
The way you choose to implement an action (with or without Direct-vuex) shouldn't change the unit test. You could try:

```ts
export const getSomeValues = (
        context,
	{ label }: ISomeValue,
): Promise <Array<ISomeValue> | void> => {
        const { dispatch } = rootActionContext(context);
        return SomeSvc
	.fetchData({ label })
	.then((resp) => dispatch.setSomeValues(resp));
}
```

Here, `dispatch.setSomeValues(resp)` is really just a wrapper that calls the original `dispatch('setSomeValues', resp)`.

**Comment by viT-1** [comment]
Why rootActionContext but not moduleActionContext?

**Comment by viT-1** [comment]
And another problem, dependency cycle:
actions need in storeConf/module for
`const modSomeForm = createModule(storeConf);`

and modSomeForm needed in actions for
`const { dispatch } = moduleActionContext(context, modSomeForm);`

**Comment by paleo** [comment]
> Why rootActionContext but not moduleActionContext?

Use the correct one: `rootActionContext` in the store, `moduleActionContext` in a vuex module. 

> And another problem, dependency cycle

https://github.com/paleo/direct-vuex/issues/15#issuecomment-569965035
