### ISSUE TITLE
Q: Is it correct createDirectStore with "empty" (only modules) configuration?

### ISSUE THREAD

**Issue by viT-1** [paleo/direct-vuex#26]
Can I use store from config:

```
const storeConf = {
	state: {},
	actions: {},
	getters: {},
	mutations: {},
	modules: modulesConf,
} as const;

Vue.use(Vuex);
export const { store, moduleActionContext } = createDirectStore(storeConf);
```

or I should use `getters: createGetters<{}>(),` createActions, etc?

**Comment by viT-1** [comment]
Related: https://github.com/paleo/direct-vuex/issues/25#issuecomment-575539548

**Comment by paleo** [comment]
> or I should use `getters: createGetters<{}>()`, createActions, etc?

The following helpers do nothing:
* createGetters
* createMutations
* createActions

They are implemented with: `(arg) => arg`.

So yes you can directly implement the JS object the old way.

**Comment by viT-1** [comment]
Yes, I thought so, but trying to fix jest tests all ways I can.
