### ISSUE TITLE
Q: declare module "vuex" for this.$store

### ISSUE THREAD

**Issue by viT-1** [paleo/direct-vuex#28]
How to check this code is working?

readme.md:
```
export type AppStore = typeof store
declare module "vuex" {
  interface Store<S> {
    direct: AppStore
  }
}
```

Is it means that I can use some code instead of (working)
```
import { store as vueAppStore } from '~/VueApp/store';
...
vueAppStore.dispatch.modSomeForm.getSomeValues
```

using this?
`this.$store.dispatch.modSomeForm.getSomeValues`

When I typing in VSCode `this.$store.dispatch` there is nothing about `getSomeValues` =(

**Comment by paleo** [comment]
It depends of how you implement your component. Is it with a class? Or with an object using the composition API?

**Comment by paleo** [comment]
1. Remove `VueApp.store.d.ts`.
2. In `VueApp.store.ts`, append:

```ts
type VueAppStore = typeof store;
declare module 'vuex' {
	interface Store<S> {
		direct: VueAppStore;
	}
}
```

**Comment by viT-1** [comment]
@paleo, after 1 & 2 is nothing changed
When I typing in VSCode this.$store.dispatch there is nothing about getSomeValues =(

**Comment by paleo** [comment]
Are your sure?
In your code, file `FomeForm.ts`, I can replace this line:

```ts
vueAppStore.dispatch.modSomeForm.getSomeValues({ label: 'Rome' }); 
```
… by this line:
```ts
this.$store.direct.dispatch.modSomeForm.getSomeValues({ label: 'Rome' });
```
