### ISSUE TITLE
Q: eslint: Missing return type on function (ModuleActionContext)

### ISSUE THREAD

**Issue by viT-1** [paleo/direct-vuex#29]
https://github.com/paleo/direct-vuex#in-a-vuex-module
`const mod1ActionContext = (context: any) => moduleActionContext(context, mod1)`
- Can be context typed (not any)?
- Which type of [parameters](https://github.com/paleo/direct-vuex/blob/master/types/direct-types.d.ts#L100) `<R,O>` should be in `DirectActionContext` [here](https://github.com/viT-1/systemjs-ts-es6-vue/blob/ebb2d24524f519e17246b5caf61a976ec3387a00/src/unique.blocks/SomeForm/store/actions.ts#L10)?
```
const mod1ActionContext = (context: any):
DirectActionContext<R, O> => moduleActionContext(context, mod1)
```

**Comment by paleo** [comment]
This context parameter is of type `ActionContext<S, R>` (from Vuex) but it is not important. We don't use it.

**Comment by viT-1** [comment]
I don't want to have eslint warnings about returned type of `mod1ActionContext`

**Comment by paleo** [comment]
In `DirectActionContext<R, O>`, `R` is the type of the root store object, `O` is the type of the vuex module object.

**Comment by paleo** [comment]
I guess we can close this issue?

**Comment by viT-1** [comment]
@paleo I don't understand which code should be [in my usecase](https://github.com/viT-1/systemjs-ts-es6-vue/blob/9224a895f7a2ee6a040906ac235b57147ffb2f03/src/unique.blocks/SomeForm/store/actions.ts#L13):

`const getTypedContext = (ctx: any) => moduleActionContext(ctx, modSomeForm);`

**Comment by paleo** [comment]
Maybe something like:

```ts
const getTypedContext = (ctx: any) => moduleActionContext(ctx, modSomeForm) as DirectActionContext<never, typeof modSomeForm>;
```

But I guess that useless rules from the linter should just be disabled.

**Comment by viT-1** [comment]
@paleo Typescript declarations are not useless =))
