### ISSUE TITLE
Is there a way to get direct-vuex to work with vuex-module-decorators?

### ISSUE THREAD

**Issue by lundmikkel** [paleo/direct-vuex#33]
I'm using [vuex-module-decorators](https://github.com/championswimmer/vuex-module-decorators) (quick intro [here](https://championswimmer.in/vuex-module-decorators/)) to write my Vuex modules. This allows me to write class-style modules that are really nice to read and write. However, [it is a bit more annoying to get a typed state](https://championswimmer.in/vuex-module-decorators/pages/getting-started.html#use-in-store) though.

Is there a way to use direct-vuex together with vuex-module-decorators? I'm currently getting problems when I try to create the direct store with my VuexModule from vuex-module-decorators:

``` js
// mymodule.ts
@Module({
  name: "MyModule",
  namespaced: true as true
})
export default class MyModule extends VuexModule {
  // ...
}

// store.ts
const { store, rootActionContext, moduleActionContext } = createDirectStore({
  modules: {
    MyModule
  }
});
```

**Comment by paleo** [comment]
I think it's not possible but I'm unsure. Is there a way to see decorated members as modified types?

For example, in [this example](https://championswimmer.in/vuex-module-decorators/pages/core/mutations.html#mutations), could it be possible to see that the property `puncture` of type `Vehicle` is a subtype of `Mutation`?

**Comment by lundmikkel** [comment]
I'm not sure. I don't know the inner workings of either library. I'm just a user, that thinks both libraries have some nice features, that the others could use :)

**Comment by paleo** [comment]
I don't see how to do that, it's probably impossible. So I close the issue. If I ever find a way to do something, then it will be time to reopen the issue and consider whether the implementation is worthwhile.
