### ISSUE TITLE
[0.10.4][Q] Working in the UI but failing for Jest

### ISSUE THREAD

**Issue by jesusgn90** [paleo/direct-vuex#35]
Please, help me to understand why this is failing. I started to use this awesome module, however, I'm facing some troubles with Jest.

Here is my **module index.ts** (mainly the same but I cannot paste code here due to NDA):

```js
// store/modules/my-module/index.ts
...
export const getDefaultState = (): CoreState => {
  return {
    ...
  }
}

// Deep clone the default state to the store state object:
const state = (): CoreState => getDefaultState()

const myModule = {
  namespaced: true as true,
  state,
  getters,
  actions,
  mutations,
}

export const myModuleActionContext = (context: any) => moduleActionContext(context, myModule)
export const myModuleGetterContext = (args: [any, any, any, any]) => moduleGetterContext(args, myModule)
export default myModule
```

And here is how I create my (big) store:

```js
...
import myModule from '@store/modules/my-module'
...
import { createDirectStore } from 'direct-vuex'

...

const {
  store,
  rootActionContext,
  moduleActionContext,
  moduleGetterContext,
} = createDirectStore({
  state,
  actions,
  getters,
  mutations,
  modules: {
    ...
    myModule,
    ...
  },
  strict: true,
})
const original = store.original
// Export the classic Vuex store.
export default original

const direct = store
export {
  // The following exports will be used to enable types in the
  // implementation of actions.
  rootActionContext,
  moduleActionContext,
  moduleGetterContext,
  // Export the direct-store
  direct,
}

// The following lines enable types in the injected store '$store'.
export type AppStore = typeof store
declare module 'vuex' {
  interface Store<S> {
    direct: AppStore
  }
}
```

And then, my test file:

```js
import { direct as store } from '@store'
describe('My module store', () => {
  ...
  const myModuleState = store.state.myModule
  const rootState = store.state
  const vueState = {
    state: myModuleState,
    store,
    rootState,
    rootGetters: store.getters,
    mockedActions: actions,
  }

  // Test mutations
  test('Store mutation: X', () => {
   ...
  })
  ...
```

The **error** is about this:

```
TypeError: Cannot read property 'getters' of undefined
```

**Comment by paleo** [comment]
Probably an issue due to circular dependencies. If you don't use any `rootXxx` in the action and getter contexts, then I suggest to use [`localGetterContext` and `localActionContext`](https://github.com/paleo/direct-vuex#alternatively-use-localgettercontext-and-localactioncontext) instead of `moduleActionContext` and `moduleGetterContext`.

**Comment by jesusgn90** [comment]
> Probably an issue due to circular dependencies. If you don't use any `rootXxx` in the action and getter contexts, then I suggest to use [`localGetterContext` and `localActionContext`](https://github.com/paleo/direct-vuex#alternatively-use-localgettercontext-and-localactioncontext) instead of `moduleActionContext` and `moduleGetterContext`.

Thanks for the response, however, I have things like this in some actions for example:

```js
const { commit, rootCommit, rootDispatch, rootGetters } = myModuleActionContext(context)
```

Also, I have things like this in some getters:

```js
const { getters, rootGetters } = myModuleGetterContext(context)
```

**Comment by jesusgn90** [comment]
However, I have a doubt, I'm using for example `rootCommit` because before this, I had `commit(SOME_MUT, payload, { root: true })` but some mutation is from a different module though. Now I translated it to `rootCommit.SOME_MUT(payload)`

**Comment by paleo** [comment]
> Now I translated it to `rootCommit.SOME_MUT(payload)`

It's fine you are right.

So I don't have an idea on how to make things work with Jest. I thought this situation occurs [when the main store source file is not imported first](https://github.com/paleo/direct-vuex/#about-direct-vuex-and-circular-dependencies). But in your code it seams you import only the store so I don't know why the execution fails.

**Comment by jesusgn90** [comment]
> But in your code it seams you import only the store so I don't know why the execution fails.

Not really dude, my code was obfuscated (due to NDA), now I've switched the import(s) order and now it passed the tests except three of them because a getter is using `rootGetters` but at the same time I'm using the localGetterContext!

**Comment by paleo** [comment]
Yep. `localGetterContext` doesn't provide `rootGetters`. You'll have to use `moduleGetterContext` for that.

**Comment by paleo** [comment]
I think we're done here.
