### ISSUE TITLE
[0.10.4][Limitation] Mutation names not being validated

### ISSUE THREAD

**Issue by jesusgn90** [paleo/direct-vuex#36]
So, more things around this library (which looks powerful!):

```js
  async someAction (context, { someParameter, someOtherParam = true }: { someParameter: any, someOtherParam?: boolean }) {
    const { commit, rootDispatch } = myModuleActionContext(context)
    commit.fff()
   ...
```
the line `commit.fff()` should not work, at compile time, at lint time or any other place but `fff` is not a valid mutation. 

On the other hand, `commit.` properly autocompletes available mutations and hovering over one of them properly shows the types. So `commit.validMutation()` properly shows me the types.

What I need is to catch when I'm using `commit.fff()` because `fff` doesn't exist.

This is also happening with other use cases, but this clearly shows the problem.

Regards dude!

**Comment by paleo** [comment]
But `commit.fff()` should not compile if `fff` is not a mutation.

**Comment by jesusgn90** [comment]
It does, how I can prevent, what should I review?

**Comment by paleo** [comment]
Maybe the type of the `mutations` property is not correctly inferred?
It's hard to say without an example.

**Comment by jesusgn90** [comment]
Ok, here is how my mutations for that module look like:

```js
const mutations = defineMutations<CoreState>()({
  // Standard store reset.
  [STRING.FROM_AN_ENUM]: (state) => {
    Object.assign(state, getDefaultState())
  },
.... // Rest of mutations ..
})
export { mutations }
```

This is how a defined the module:

```js
const myModule = defineModule({
  namespaced: true,
  state,
  getters,
  actions,
  mutations, // <---- import { mutations } from './mutations'
})
```

And then in my action, I can't catch the `commit.fff()` as my first comment says.

Do you need more context about this? just ask please, I really like this library but need it 100% working

**Comment by paleo** [comment]
Can you try to replace all the `[STRING.FROM_AN_ENUM]` with the real mutation names? Perhaps TypeScript can't infer the literal name of the mutation and fall back on string...

**Comment by jesusgn90** [comment]
> Can you try to replace all the [STRING.FROM_AN_ENUM] with the real mutation names? Perhaps TypeScript can't infer the literal name of the mutation and fall back on string...

Already tested this and same result dude

**Comment by paleo** [comment]
It should work. I use exactly this kind of code and when I write `commit.fff()` (with `fff` not defined) then the TS compiler correctly complains.

**Comment by jesusgn90** [comment]
It should, but I'm probably missing something, if I figure it out, I'll tell you here

**Comment by paleo** [comment]
If it can help: in your IDE, you should look at the type of the object `mutations` here:

```ts
const mutations = defineMutations<CoreState>()({
```

With VS Code you just have to hover `mutations` with the mouse cursor and all the details of the functions must appear: you should see each name, each parameter with the correct type, etc.

**Comment by jesusgn90** [comment]
> If it can help: in your IDE, you should look at the type of the object `mutations` here:
> 
> ```ts
> const mutations = defineMutations<CoreState>()({
> ```
> 
> With VS Code you just have to hover `mutations` with the mouse cursor and all the details of the functions must appear: you should see each name, each parameter with the correct type, etc.

Yeah, and it does the job perfectly. The problem is that something like `commit.ffff()` if I hover just says `any`. That's nice coz if I hover over something that says `any`, it means that thing doesn't exist. So my goal is to make that `commit.something` can never be `any`.

At this point I think that since I have a huge mix of modules (namespaced and not namespaced, TS and JS, different syntax styles...) it may be relying on this as valid, maybe once I migrate all of them, types are more strict.

**Comment by jesusgn90** [comment]
@paleo now I got the answer to this quantic-problem:

If you use `createDirectStore` with a mix of modules, where some of them are using direct-vuex and some of them not yet, then the types are a bit relaxed for the `commit.ffffffffasd()` use case. However, if all the modules are using direct-vuex, then it works like a charm.

```js
// Infer all types like a charm
createDirectStore({
  state,
  actions,
  getters,
  mutations,
  modules: {
     module_that_uses_direct_vuex_1,
     module_that_uses_direct_vuex_2,
  },
  strict: true,
})

// Limitation coz TS can't properly infer if commit.fffffasda() exists, 
// and it accepts any
createDirectStore({
  state,
  actions,
  getters,
  mutations,
  modules: {
     module_that_uses_direct_vuex_1,
     module_that_DO_NOT_uses_direct_vuex_2,
  },
  strict: true,
})
```

Putting this here just FYI or any other user with a large project.
