### ISSUE TITLE
Optional payloads not detected

### ISSUE THREAD

**Issue by jaredmcateer** [paleo/direct-vuex#38]
I have an action where I want it to be called with either a payload or nothing. 

```ts
actions: {
  async myAction(context, payload?: PayloadType) {
    // ...
  }
}
```

```ts
store.dispatch.myAction();
               ^---------- Expected 1 arguments, but got 0.ts(2554)
                           direct-types.d.ts(97, 7): An argument for 'payload' was not provided.
```

I also tried `async myAction(context, payload: PayloadType | undefined)` but got the same error.

For now I've worked around the issue by passing in `null` but it would be nice if it were possible to make the parameter optional.

**Comment by thanhchungbtc** [comment]
I think we would add the condition where the payload is optional in `direct-types.d.ts`, have tried something but still not figure it out. Any suggestion?

```ts
type ToDirectActions<T extends ActionsImpl> = {
  [K in keyof T]: Parameters<T[K]>[1] extends undefined
  ? (() => PromiseOf<ReturnType<T[K]>>)
  : ((payload: Parameters<T[K]>[1]) => PromiseOf<ReturnType<T[K]>>)
}
```

**Comment by 5eraph** [comment]
Hi, bellow code works for me:
```ts
type ToDirectActions<T extends ActionsImpl> = {
    [K in keyof T]: Parameters<T[K]>[1] extends undefined
    ? (() => PromiseOf<ReturnType<T[K]>>)
    : (Extract<Parameters<T[K]>[1], undefined> extends never ? 
        ((payload: Parameters<T[K]>[1]) => PromiseOf<ReturnType<T[K]>>) :
        ((payload?: Parameters<T[K]>[1]) => PromiseOf<ReturnType<T[K]>>))
}
```
~~with exception that instead of `payload` only, it says `payload 0`.~~
works as expected.

**Comment by jaredmcateer** [comment]
Thanks @5eraph!
