### ISSUE TITLE
[Feature] Stronger typed modules?

### ISSUE THREAD

**Issue by SaphuA** [paleo/direct-vuex#4]
Vuex has a very useful generic `StoreOptions` type to define stores:
```ts
const module: StoreOptions<UserState> = {
    state: {
        name: "Harry Potter"
    },
    getters: {
        name: (state) => state.name // Here state automatically has the correct type UserState
    }
}
```
This is how the same store should be defined with `direct-vuex`. On larger stores this adds quite some bloat:

```ts
export default {
    state: {
        name: "Harry Potter"
    } as UserStore,
    getters: {
        name: (state: UserStore) => state.name
    }
}
```

Unless I'm mistaken there is no way to use this (or any other) type to achieve the same thing, because of the const assertion. Do you know if there's another way to make store creation stronger typed?

**Comment by paleo** [comment]
Maybe it is possible with a wrapper function `createModule`, like the wrapper function `createComponent` in the composition API. I'll try.

**Comment by Cmacu** [comment]
I've started using direct-vuex yesterday and immediately encountered this too. Thanks for looking into it.

**Comment by paleo** [comment]
I did something. Please update to the version 0.8 and try to use `createModule`:

```ts
export default createModule({
    state: {
        name: "Harry Potter"
    } as UserStore,
    getters: {
        name: state => state.name // type of 'state' is 'UserStore'
    }
})
```

Be careful: **`as const` must not be used with the helper `createModule`.** Just remove `as const` if you had it before.

See also: https://github.com/paleo/direct-vuex#in-a-vuex-module

**Comment by SaphuA** [comment]
Great work! Going to have a look tomorow!

**Comment by paleo** [comment]
I guess I can close this issue. Let me know in a new issue if you find a bug.

**Comment by SaphuA** [comment]
Sorry haven't had a chance to look at it yet - but it looks great! If I find issues I'll let you know.
