### ISSUE TITLE
Property 'alert' does not exist on type 'never'.

### ISSUE THREAD

**Issue by vpekarek** [paleo/direct-vuex#41]
Hello,
I think that your product is super. But I have some problems with it and I was not able to google it.
When I typing the project, everything looks fine. But when I try to build it, i got error:

Property 'alert' does not exist on type 'never'.

Instead of 'alert' you can put any of my vuex store module. In development build it is compiled with this error, but everything works fine.

    const SUCCESS = 'success';
    const WARNING = 'warning';
    const ERROR = 'error';
    const CLEAR = 'clear';

    const state: AlertStore = {
        type: null,
        message: null
    }
    const mutations = {
        [SUCCESS](state: AlertStore, message: string) {
            state.type = AlertType.Success;
            state.message = message;
        },
        [WARNING](state: AlertStore, message: string) {
            state.type = AlertType.Warning;
            state.message = message;
        },
        [ERROR](state: AlertStore, message: string) {
            state.type = AlertType.Error;
            state.message = message;
        },
        [CLEAR](state: AlertStore) {
            state.type = null;
            state.message = null;
        },
    };
    
    const actions = {
        success({ commit }: any, message: string) {
            commit(SUCCESS, message);
            },
        warning({ commit }: any, message: string) {
            commit(WARNING, message);
        },
        error({ commit }: any, message: string) {
            commit(ERROR, message);
        },
        clear({ commit }: any) {
            commit(CLEAR);
        },
    };
    
    const getters = {};
    
        export interface AlertStore {
        type: AlertType | null;
        message: string | null;
    }

    export enum AlertType {
        Success = 'success',
        Warning = 'warning',
        Error = 'error',
    }
    
    export default {
        namespaced: true as true,
        state: state as AlertStore,
        getters,
        actions,
        mutations
    };

Calling `store.dispatch.alert.clear()` show error, that alert does not exist on type 'never'. Pointing to 'dispatch'. The same with 'getters'.

**Comment by paleo** [comment]
Maybe the problem is where the store is created?

**Comment by vpekarek** [comment]
Hi. I tried the example mod1 store, but it is not working in Typescript for me.

Here is my app:
[test-app.zip](https://github.com/paleo/direct-vuex/files/4399219/test-app.zip)

I tried to use module without `defineModule`, but it was the same problem. Not possible to build app.

store/mod1.module.ts

    export interface Mod1State {
      p1: string
    }

    const state: Mod1State = {
      p1: ''
    };

    const mod1 = {
      namespaced: true as true,
      state: state as Mod1State,
      getters: {
        p1OrDefault(state: Mod1State) {
          return state.p1 || "default"
        }
      },
      mutations: {
        SET_P1(state: Mod1State, p1: string) {
          state.p1 = p1
        }
      },
      actions: {
        loadP1(payload: string) {
        }
      },
    }

    export default mod1;


store/index.ts


    import Vue from 'vue';
    import Vuex from 'vuex';
    import { createDirectStore } from "direct-vuex"

    // import alert from './alert.module';
    import mod1 from './mod1.module';

    Vue.use(Vuex);

    const { store, rootActionContext, moduleActionContext, rootGetterContext, moduleGetterContext } = createDirectStore({
      strict: process.env.NODE_ENV !== 'production',
      modules: {
        mod1
      }
    });

    // Export the direct-store instead of the classic Vuex store.
    export default store;

    // The following exports will be used to enable types in the
    // implementation of actions.
    export { 
        rootActionContext, 
        moduleActionContext, 
        rootGetterContext, 
        moduleGetterContext
    };

    // The following lines enable types in the injected store '$store'.
    // @ts-ignore <- ignore it
    export type AppStore = typeof store
    declare module "vuex" {
      interface Store<S> {
        direct: AppStore
      }
    }


main.ts

    import Vue from 'vue';
    import router from './router';
    import App from './App.vue';
    import store from './store';

    Vue.config.productionTip = true;

    // @ts-ignore <- ignore it
    new Vue({
        router,
        store: store.original, // Inject the classic Vuex store
        components: { App },
        render: (h: any) => h(App),
    }).$mount('#app');

**Comment by vpekarek** [comment]
Ok, on different project, this works ok. I will dig deeper, to find difference. Just now keep it open.
