### ISSUE TITLE
type safety for the ActionContext

### ISSUE THREAD

**Issue by thanhchungbtc** [paleo/direct-vuex#42]
Thanks for the great library.
I like how simple the idea is most importantly, do not need to change much code from the traditional vuex approach.

### The problem
However, it would be awesome if we can use strongly type for the ActionContext.
For example,

```ts
actions: {
  fetchSomething({state, rootState}, payload: SomePayload) {  
  }
}
```

### Expected behavior
 `state` and `rootState` should be of type `ModuleState` and `RootState`, instead of `any`.

**Comment by vintprox** [comment]
Yep, this library is lit.

By the way, I cannot get typing for actions with `localActionContext`/`moduleActionContext`. 😵

**Comment by vintprox** [comment]
OMG! I've just found out that typings ducked up because I didn't specify desired return type for action:
```
import { defineActions } from 'direct-vuex';
import { Route, RouteConfig } from 'vue-router';
import { moduleActionContext } from '@/store';
import panels from './index';

const action = (context: any) => moduleActionContext(context, panels);

export default defineActions({
  push(context, route: Route) {
    const { commit, getters } = action(context);
    ...
  },
});
```

```
  push(context, route: Route): Route | RouteConfig {
```

**Comment by paleo** [comment]
@thanhchungbtc You can use `moduleActionContext`. The documentation [is here](https://github.com/paleo/direct-vuex#implement-a-vuex-store-with-typed-helpers).

@vintprox Yes, you found the solution. I mentioned this issue in a warning at the end of [this section](https://github.com/paleo/direct-vuex#in-a-vuex-module):

> Types in the context of actions implies that TypeScript should never infer the return type of an action from the context of the action. Indeed, this kind of typing would be recursive, since the context includes the return value of the action. When this happens, TypeScript passes the whole context to any. Tl;dr; Declare the return type of actions where it exists!

**Comment by thanhchungbtc** [comment]
> @thanhchungbtc You can use `moduleActionContext`. The documentation [is here](https://github.com/paleo/direct-vuex#implement-a-vuex-store-with-typed-helpers).

Thanks. It works but IMHO not feel very natural since we have to inject that boilerplate code to every action.

The traditional Vuex approach uses for e.g`Module<ModuleState, RootState>` to create a module with strongly type ActionContext, so it would be great if we can also specify states in `defineActions` or `defineModule` like that.

**Comment by vintprox** [comment]
Welp, let's just wait for new Vuex release and Vue 3. 🙂
For the time being, `direct-vuex` is really to the rescue! 🚀 Thank you very much, @paleo 🎉

**Comment by vintprox** [comment]
Also, hooo boie if I'm not used to typing `store.state.module.*` with direct-vuex! 😍💯 You even can say it became more natural approach to me than traditional Vuex. 🍉
Definitely looking forward to see how things are integrated with new releases of core dependencies.
