### ISSUE TITLE
Namespaced related wording in documentation

### ISSUE THREAD

**Issue by Sorceror** [paleo/direct-vuex#48]
First, than you very much for making vuex finally usable with TypeScript! 👍

Reading this

> Direct-vuex provides several useful helpers for implementation of the store. They are all optional. However, if you want to keep your classic implementation of a Vuex Store, then direct-vuex needs to infer the literal type of the namespaced property. **You can write namespaced: true as true where there is a namespaced property. But you don't need to worry about that if you use defineModule.**

it seems to me that I don't have to write `namespaced: true as true` to a module definition when I'm using `defineModule` helper function. But that does not seem to be true. 
  
When `namespaced` attribute is omitted everything is registered in global state as expected from the documentation https://vuex.vuejs.org/guide/modules.html#namespacing .

Is that just unfortunate wording or am I doing something wrong and using `defineModule` should create namespaced module automatically?

#17

**Comment by paleo** [comment]
The explanation was about `as true`. You still need `namespaced: true`. ;-)
