### ISSUE TITLE
IE 11 Expected ':'

### ISSUE THREAD

**Issue by vpekarek** [paleo/direct-vuex#49]
Hi,
i have problem with running the app in IE 11. The problem i in function createDirectStore(options), where it exptect `original: original`, insead of  simple `original` in `const store { ... }`

    function createDirectStore(options) {
    const original = new vuex__WEBPACK_IMPORTED_MODULE_0__["default"].Store(options);
    const store = {
        get state() {
            return original.state;
        },
        getters: toDirectGetters(options, original.getters),
        commit: toDirectCommit(options, original.commit),
        dispatch: toDirectDispatch(options, original.dispatch),
        original
    };
    original.direct = store;
    return {
        store,
        rootGetterContext: ([state, getters]) => getModuleGetterContext([state, getters, state, getters], options, options),
        moduleGetterContext: (args, moduleOptions) => getModuleGetterContext(args, moduleOptions, options),
        rootActionContext: (originalContext) => getModuleActionContext(originalContext, options, options),
        moduleActionContext: (originalContext, moduleOptions) => getModuleActionContext(originalContext, moduleOptions, options),
    };
}

Is there a way to fix this? Thanks

**Comment by vpekarek** [comment]
Ok, fixed it with `transpileDependencies: ['direct-vuex']` in  vue.config.js

**Comment by Sorceror** [comment]
IE11 does not support shorthand notation for object literals (and other parts of ES6 = ES2015) https://caniuse.com/#feat=mdn-javascript_grammar_shorthand_object_literals http://kangax.github.io/compat-table/es6/#test-object_literal_extensions .
 
Could be also solved by recompiling direct-vuex with `ES5` option https://github.com/paleo/direct-vuex/blob/master/tsconfig.json#L4 .

Just from curiosity, why the IE11 support? It's a hard project requirement? It's in my humble opinion dead browser already.

**Comment by vpekarek** [comment]
The final app will be part of the e-commerce website with fashion. The website has still about 5% viewers from IE 11. I am not happy about that, but can't do much about it. It is still 5% of the money :-D
