### ISSUE TITLE
[Feature] Swap command and module order?

### ISSUE THREAD

**Issue by SaphuA** [paleo/direct-vuex#5]
Currently to access a module action you can do: `this.$store.direct.dispatch.users.someAction()`

Although I am wondering if it would make more sense (and be possible) to swap the order of the command (dispatch) and the module (users), like so: `this.$store.direct.users.dispatch.someAction()`

The benefit of the latter is that it makes it possible to return the module as a calculated property in your component to reduce bloat:
```ts
export default class UserManagement extends Vue {
  private get users() {
    return this.$store.direct.users;
  }

  public someAction() {
    this.users.dispatch.someAction();
  }
}
```
Or even better in the template:
```vue
<h2 class="title">{{users.getters.name}}</h2>
```

Just an fyi I'm now doing this to achieve the same thing:
```ts
  private get users() {
    return {
      state: this.$store.direct.state.users,
      getters: this.$store.direct.getters.users,
      commit: this.$store.direct.commit.users,
      dispatch: this.$store.direct.dispatch.users,
    }
  }
```

**Comment by paleo** [comment]
Hi. I prefer not to do that. I agree with you: it would be more logical. But direct-vuex aims to remain a wrapper the less intrusive as possible for Vuex users.
