### ISSUE TITLE
Types are lost when loading modules via registerModule

### ISSUE THREAD

**Issue by andrewz-skyward** [paleo/direct-vuex#50]
I'd like to dynamically register modules via store.original.registerModule, but types registered this way are not detected.  Is this a feature that can be added, or am I doing something wrong?

**Comment by paleo** [comment]
Hi. Maybe it would be possible to add the module types using [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html). But this operation would  statically add the types during compilation for all the code of the application. With `registerModule` a module can be conditionally added, or its name can be dynamically chosen. This kind of feature can't be reproduced in types.

Direct-vuex aims to be a patch for lacks of typing in Vuex 3 and I will work to keep it compatible with Vuex 4. But this project will probably become unecessary with the redesign of Vuex 5. It is not a definitive solution that would be improved for each side-case. A pull request would of course be welcome, but I don't intend to work on this feature myself.
