### ISSUE TITLE
When I return an Rxjs Observable, the return type is `Promise<Observable<any>>`

### ISSUE THREAD

**Issue by rostamiani** [paleo/direct-vuex#54]
I'm using Rxjs Observables in my actions. When using `defineActions`, action functions return Promises. How can I return Observables?

When I return an Rxjs Observable, the return type is `Promise<Observable<any>>`

How can I return an Observable?

**Comment by paleo** [comment]
You can't. I just wrote types that reflect what Vuex does. By design, the `dispatch` function of Vuex is always asynchronous and returns a promise.
