### ISSUE TITLE
How to test an action?

### ISSUE THREAD

**Issue by mspoulsen** [paleo/direct-vuex#6]
Hi,

Thanks for writing this great library. I can't believe this is not built into vuex. I hope vuex + typescript will be a better match once vue3 is out.

Anyway, my question is: how can I test an action now that we use moduleActionContext inside the actions?

I get: 
```
TypeError: Invalid value used as weak map key

export const fooActionContext = (context: any) =>
    moduleActionContext(context, fooModule)

```

My code is:
```javascript

// foo.ts
import { Context } from './types';
import { fooActionContext } from './store';

export const actions = {
  foo(context: Context) {
    const { commit } = fooActionContext(context)
  }
} as const



// fooModule.ts
import { actions } from './foo';

export const fooModule = {
  namespaced: true,
  state: {},
  getters: {},
  actions,
  mutations: {}
} as const



// foo.test.ts
import { actions } from './foo';

test("foo", async () => {
  const commit = jest.fn()
  await actions.foo({ commit } as any)

  expect(commit).toHaveBeenCalled()
})


// store.ts
import Vue from 'vue';
import Vuex from 'vuex';
import { createDirectStore } from 'direct-vuex';
import { fooModule } from './fooModule';

Vue.use(Vuex)

export const { moduleActionContext } = createDirectStore({
  state: {},
  modules: {
    fooModule
  }
} as const)

export const fooActionContext = (context: any) =>
  moduleActionContext(context, fooModule)


```

What am I doing wrong? And how should I test an action how that we call fooActionContext() inside the action?

Thanks in advance!

**Comment by paleo** [comment]
Internally, I use the original 'dispatch' function as a key for a cache. I've just disabled the cache if 'dispatch' is not defined. Please update to the version 0.7.6 and test again.

**Comment by mspoulsen** [comment]
I upgraded and it is working now! Thanks! :tada: 

Quick question:

I typecast the object with the spy function as any:
```javascript
await actions.foo({ commit } as any)
```

Is there a better approach so that I can avoid using any?

**Comment by mspoulsen** [comment]
Another thing. If I add an action bar:

```javascript
export const actions = {
  foo(context: Context) {
    const { commit, dispatch } = fooActionContext(context)
    dispatch.bar()
    commit.FOO()
  },
  bar(context: Context) {
    console.log("bar")
  }
} as const
```

And then try to test it:

```javascript
import { actions } from './foo';

test("foo", async () => {
  const commit = jest.fn()
  const dispatch = jest.fn()
  await actions.foo({ commit, dispatch } as any)

  expect(commit).toHaveBeenCalled()
  expect(dispatch).toHaveBeenCalledWith()
})
````

Then I get: 

```
TypeError: dispatch.bar is not a function

    6 |   foo(context: Context) {
    7 |     const { commit, dispatch } = fooActionContext(context)
>  8 |     dispatch.bar()
       |              ^
    9 |     commit.FOO()
  10 |   },
  11 |   bar(context: Context) {
```

Maybe not so strange. But then I would expect the same error with commit?

Can you provide an example on how to test actions when using this library? It is a little different than passing dispatch/commit in as spies like we usually do :slightly_smiling_face:

**Comment by paleo** [comment]
In `foo.test.ts`, add an import: `import './store'` at the first line.

There is a mutual import due to `fooActionContext`.

```ts
export const fooActionContext = (context: any) =>
  moduleActionContext(context, fooModule)
```

At build time it is OK. But at runtime, if the actions are imported first, then, in `fooActionContext`, the `fooModule` object has properties `actions` and `mutations` set to `undefined`. That's why at runtime `dispatch` and `commit` are both empty objects in the `foo` action.

**Comment by paleo** [comment]
> Is there a better approach so that I can avoid using any?

You could declare the action without a `Context` type:

```ts
foo(context: any) {
```

It is valid IMHO because we don't use anything directly in this context object.

**Comment by mspoulsen** [comment]
Hmmm....my sort-typescript-imports vscode extension is preventing me from importing store on the first line :laughing: 
If I disable the extension it works...hmmm...I will think about what to do.

Btw, I really like the changes in 0.8. Much nicer! :+1: 
Thanks again!

**Comment by paleo** [comment]
Maybe you could try the old way?

```ts
require("./store")
```

EDIT: Or, you could rename `store.ts` to `a-store.ts` (because "a" will appear before "f").
Or, try to rename `store.ts` to `index.ts` and then: `import '.'` should appear first.
Or, remove your plugin and use a setting of the vanilla VS Code:

```json
  "editor.codeActionsOnSave": {
    "source.organizeImports": true
  },
```

**Comment by mspoulsen** [comment]
Thanks for the tips! I will find a solution that works 🙂

**Comment by paleo** [comment]
I think I can close this issue.
