### ISSUE TITLE
Usage trouble?: Implementation with vue3, vuex 4 and modules

### ISSUE THREAD

**Issue by d0peCode** [paleo/direct-vuex#66]
Hi, I was looking for some easier way to implement fully typed structure into vuex 4. I encounter some issue when implementing this library

My main.ts file 

```ts
import { createApp } from "vue";
import App from "./App.vue";
import "./registerServiceWorker";
import router from "./router";
import store from "./store";

createApp(App)
  .use(store.original)
  .use(router)
  .mount("#app");
```

my store main file (index.ts)

```ts
import { createStore } from "vuex";
import { createDirectStore } from "direct-vuex"
import { counter } from './counterModule/index'

const {
  store,
  rootActionContext,
  moduleActionContext,
  rootGetterContext,
  moduleGetterContext
} = createDirectStore({
  // … store implementation here …
  // root:
  state: {},
  getters: {},
  mutations: {},
  actions: {},
  // module:
  modules: {
    counter
  }
})

// Export the direct-store instead of the classic Vuex store.
export default store

// The following exports will be used to enable types in the
// implementation of actions and getters.
export {
  rootActionContext,
  moduleActionContext,
  rootGetterContext,
  moduleGetterContext
}

// The following lines enable types in the injected store '$store'.
export type AppStore = typeof store
declare module "vuex" {
  interface Store<S> {
    direct: AppStore
  }
}
```

and my coutnerModule/index.ts is:

```ts
/* eslint-disable no-use-before-define */
import { defineModule } from "direct-vuex"
import { moduleActionContext, moduleGetterContext } from "../index"

export interface CounterState {
  counter: number
}

const counter = defineModule({
  state: (): CounterState => {
    return {
      counter: 0
    }
  },
  getters: {
    counter(): number {
      const { state, getters, rootState, rootGetters } = counterGetterContext()
      // Here, 'getters', 'state', 'rootGetters' and 'rootState' are typed.
      // Without 'mod1GetterContext' only 'state' would be typed.
      return state.counter
    }
  },
  mutations: {
    SET_COUNTER(state, counter: number): void {
      // Here, the type of 'state' is 'CounterState'.
      state.counter = counter
    }
  },
  actions: {
    fetchCounter(context, payload: { counter: number }) {
      const { dispatch, commit, getters, state } = counterGetterContext()
      // Here, 'dispatch', 'commit', 'getters' and 'state' are typed.
      setTimeout(() => {
          console.log('commit', commit)
      }, 1500)
    }
  },
})

export { counter }
const counterGetterContext = () => moduleGetterContext(counter)
const counterActionContext = (context: any) => moduleActionContext(context, counter)
```

Here in my IDE says 

> Property 'commit' does not exist on type '{ rootState: { readonly counter: DirectState<{ state: () => CounterState; getters: { counter(): number; }; mutations: { SET_COUNTER(state: CounterState, counter: number): void; }; actions: { ...; }; }>; }; rootGetters: { ...; }; state: { ...; } | { ...; }; getters: {} | { ...; }; }'

when i hover `commit` within the action. Also in devtools console there's issue with basically same message.

What I did wrong here?

**Comment by paleo** [comment]
You forgot the arguments:
```ts
const counterGetterContext = (args: [any, any, any, any]) => moduleGetterContext(args, counter)
```
In the getter `counter`, you should pass the arguments.

In the action `fetchCounter`, you should call `moduleActionContext`.

**Comment by d0peCode** [comment]
I changed as you pointed. Now I wonder why do I need to call dispatch from function like this:

```ts
<template>
  {{ counter }}
  <button @click="inc">inc</button>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import store from '../store/index'

export default defineComponent({
  name: "HelloWorld",

  computed: {
    counter () {
      return store.getters.counter
    }
  },

  methods: {
    inc () {
      store.dispatch.fetchCounter({ counter: 2})
      // store.dispatch.counter.fetchCounter({ counter: 2})
      console.log('store', store)
    }
  }
});
</script>
```

since this line

```store.dispatch.counter.fetchCounter({ counter: 2})```

was giving an error:

> Property 'counter' does not exist on type '{ fetchCounter: (payload: { counter: number; }) => Promise<void>; incCounter: (payload: { by: number; }) => Promise<void>; }'.Vetur(2339)

this is the store log

![image](https://user-images.githubusercontent.com/40339232/106611232-0502b600-6568-11eb-93a4-5f9178af06c5.png)

while I imported main store index file (not a module)

**Comment by paleo** [comment]
Maybe because your module is not namespaced.

**Comment by d0peCode** [comment]
Yes! Thank you very much. This lib seems to be awesome. Last questions:

I tried to `mapActions` is it possible with modules while using this lib? I tried like this:

```ts
<template>
  {{ counter }}
  <button @click="changeCounterMethod(-1)">decCounter</button>
  <button @click="changeCounterMethod(1)">incCounter</button>
  <button @click="fetchCounter">fetchCounter</button>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { mapActions } from "vuex";
import store from '../store/index'

export default defineComponent({
  name: "HelloWorld",

  computed: {
    counter (): number {
      return store.getters.counter.counter
    }
  },

  ...mapActions([
    'counter/changeCounter'
  ]),

  methods: {
    changeCounterMethod (by: number): void {
      store.dispatch.counter.changeCounter({ by }) // works
      this.changeCounter(by) // doesnt work obviously
    },
    fetchCounter (): void {
      store.dispatch.counter.fetchCounter({ counter: 2 })
    }
  }
});
</script>
```

Also I would prefer to use the store via `this.$store`. I tried adding it to globalProperties after creatingApp

```ts
app
  .use(store.original)
  .use(router)
  .mount("#app");

app.config.globalProperties.$store=store.original;

console.log('app.config.globalProperties', app.config.globalProperties)
  ```

( i tried store.original and just store )

and it's actually there

![image](https://user-images.githubusercontent.com/40339232/106628302-f1f8e180-6579-11eb-8892-8e81fe8aaefd.png)

but within component options API it's still undefined. Any ideas?

**Comment by paleo** [comment]
No, I didn't found a way to create types for `mapActions`. However it should work (without typings) because Direct-vuex is a wrapper around Vuex and it is still the classic Vuex that is integrated to the Vue components. I don't use `mapActions` so I don't have any experience with it.

**Comment by d0peCode** [comment]
What about `this.$store` why i can't use it in components options api? For example in `created()` hook.

**Comment by paleo** [comment]
It should work the same way as usual.

**Comment by d0peCode** [comment]
May you please take a look at the demo repository? https://github.com/d0peCode/vuex-ts-modules-demo-2 It's just a counter I try to use this.$store in method in Counter.vue component and it's clearly undefined. In empty vue3 projected created with vue cli `this.$store` is working.

**Comment by paleo** [comment]
Where do you use `direct-vuex` in your project?

**Comment by d0peCode** [comment]
Oh my appologise I sent you wrong repository https://github.com/d0peCode/vuex-ts-modules-demo-1 this one is correct.
