### ISSUE TITLE
Can you bundle esm version?

### ISSUE THREAD

**Issue by viT-1** [paleo/direct-vuex#7]
It will be useful for developing with native es modules in browser.

**Comment by paleo** [comment]
Which extension do you suggest? `.esm.js` or `.mjs`?

**Comment by viT-1** [comment]
@paleo It's about `.esm.js`

**Comment by paleo** [comment]
I've done something in `dist-esm/direct-vuex.js`. The `"module"` property is set in `package.json`. Let me know if it is okay.

**Comment by viT-1** [comment]
Esm version shows me that vuex should be in "dependencies" not "[devDependencies](https://github.com/paleo/direct-vuex/blob/master/package.json#L32)".

**Comment by paleo** [comment]
I don't think so. Vuex is in peerDependencies, that means you need to choose and install your own version of Vuex.

There is actually a version of Vuex in the devDependencies of Direct-vuex, but it is just here to provide TypeScript types and to execute unit tests.

**Comment by viT-1** [comment]
@paleo May be you right but [npmjs show](https://www.npmjs.com/package/direct-vuex?activeTab=dependencies) me that direct-vuex has no dependencies - this is not quite true. May be it is a npmjs interface incorrectness.

**Comment by viT-1** [comment]
Thanks, esm version is working (only `createDirectStore(storeConf).store.original` tested)!

**Comment by viT-1** [comment]
@paleo 
v 0.9.4
It's working only with SystemJS.
But esm version using as `import DirectVuex from 'direct-vuex';` raise error:
`Uncaught SyntaxError: The requested module '/direct-vuex.esm.min.js' does not provide an export named 'default'`

Jest tell me on
```
import DirectVuex from 'direct-vuex';
...
const store = DirectVuex.createDirectStore(storeConf).store.original;

```
similar error:
`TypeError: Cannot read property 'createDirectStore' of undefined`

**Comment by paleo** [comment]
And with `import { createDirectStore } from "direct-vuex"` ?

**Comment by viT-1** [comment]
`import { createDirectStore }` is failed with SystemJS. [#14](https://github.com/paleo/direct-vuex/issues/14#issuecomment-568918493)
Thus (with `import { createDirectStore }` or `import DirectVuex from 'direct-vuex';`) I have one broken code (for SystemJs production bundle or for esm develop modules).

Both esm & umd packages should have same module using abilities

**Comment by paleo** [comment]
OK, update and try again please.
I added all the named exports as properties in an additional default export.

**Comment by viT-1** [comment]
esm is working but umd v 0.9.5 is failed on
`DirectVuex.createDirectStore(storeConf).store.original;`
with error
```
direct-vuex.umd.js:17 Uncaught (in promise) TypeError: Cannot read property 'Store' of undefined
    at Object.createDirectStore (direct-vuex.umd.js:17)
```

umd v 0.9.4 is working fine

**Comment by paleo** [comment]
It seems the dependency `Vuex` is undefined. There is no difference related to the line 17 between the 2 versions.
https://cdn.jsdelivr.net/npm/direct-vuex@0.9.4/dist/direct-vuex.umd.js
https://cdn.jsdelivr.net/npm/direct-vuex@0.9.5/dist/direct-vuex.umd.js

**Comment by paleo** [comment]
Could it be a side effect of using 'window' instead of 'this' in the TS helpers? I can revert this detail.

**Comment by viT-1** [comment]
I am using same importmap for SystemJs module dependencies resolving.
[0.9.4 umd is ok](https://github.com/viT-1/systemjs-ts-es6-vue/blob/3fb2840beb2472cb63a76c3fd10fe7a52b3b91f3/src/importmap.system.json#L3), but 0.9.5 is failed

**Comment by paleo** [comment]
I just published.
https://cdn.jsdelivr.net/npm/direct-vuex@0.9.8/dist/direct-vuex.umd.js

**Comment by viT-1** [comment]
[0.9.8 working](https://github.com/viT-1/systemjs-ts-es6-vue/commit/145a7148545ea7e109c18e7b79774156ef2cef5a) both esm & umd, thank you!
But I have some troubles with SystemJS & IE11 (may be it is not caused by migrating to direct-vuex).

**Comment by viT-1** [comment]
Yes, IE11 troubles it is another issue (sorry for writing here) caused by direct-vuex migrating.
If I [remove direct-vuex code](https://github.com/viT-1/systemjs-ts-es6-vue/commit/9fc5f15b2421b762439b4795d94bcec99743c7a9), IE11 is ok.
If not, I have error:
```
Unhandled promise rejection TypeError: unsupported method "entries"
stack: 
at gettersFromOptions (https://cdn.jsdelivr.net/npm/direct-vuex@0.9.8/dist/direct-vuex.umd.js:68:30)
at toDirectGetters (https://cdn.jsdelivr.net/npm/direct-vuex@0.9.8/dist/direct-vuex.umd.js:58:13)
at createDirectStore (https://cdn.jsdelivr.net/npm/direct-vuex@0.9.8/dist/direct-vuex.umd.js:18:9)
at e.init (http://localhost:3000/bundle.system.js:1:19479)
...
```

**Comment by viT-1** [comment]
I've just created #19
