### ISSUE TITLE
 The type 'readonly [Plugin<RootState>]' is 'readonly' and cannot be assigned to the mutable type 'PluginImpl[]

### ISSUE THREAD

**Issue by Cmacu** [paleo/direct-vuex#8]
Type error when using `createDirectStore` with `VuexPersistance` plugin:

> The type 'readonly [Plugin<RootState>]' is 'readonly' and cannot be assigned to the mutable type 'PluginImpl[]

Is there a reason PluginImp[] is mutable?

```Vue.use(Vuex);

const vuexPersistance = new VuexPersistence<RootState>({
  storage: localStorage,
});

export const {
  store,
  rootActionContext,
  moduleActionContext,
} = createDirectStore({
  modules: {
    // filter,
  },
  strict: process.env.DEV ? true : false,
  plugins: [vuexPersistance.plugin],
} as const);
```

**Comment by paleo** [comment]
There _was_ a reason. The literal type of `namespaced` had to be inferred. But I just found a solution. Update to the version 0.8, then remove `as const` from the implementation.

**Comment by Cmacu** [comment]
Great, this works!
