### ISSUE TITLE
How to use `createGetters` for getters with arguments?

### ISSUE THREAD

**Issue by koljada** [paleo/direct-vuex#9]
Thank you for adding all `createXXX` methods, they are very useful.
So far I could not figure out only one thing: how to create getters with parameters?
Something like this: https://vuex.vuejs.org/guide/getters.html#method-style-access

Is it supported? It seems like currently all getters are mapped to properties, not methods: 
![image](https://user-images.githubusercontent.com/11540537/70248026-3cae7c00-1772-11ea-9a99-000d40e7d383.png)

**Comment by paleo** [comment]
>  Something like this: https://vuex.vuejs.org/guide/getters.html#method-style-access

Sure.
In the same way as in the documentation:

```ts
  getFormDefinitionById: state => formId => state.formDefinitions.find(/* … */)
```

**Comment by koljada** [comment]
Indeed, thank you. I should have found it by myself. I guess this issues can be closed.
